/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as ApiPublicWorkerCompleteRouteImport } from './routes/api/public/worker/complete'
import { Route as ApiPublicWorkerHeartbeatRouteImport } from './routes/api/public/worker/heartbeat'
import { Route as ApiPublicWorkerIngestRouteImport } from './routes/api/public/worker/ingest'
import { Route as ApiPublicWorkerJobsRouteImport } from './routes/api/public/worker/jobs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerCompleteRoute = ApiPublicWorkerCompleteRouteImport.update({
  id: '/api/public/worker/complete',
  path: '/api/public/worker/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerHeartbeatRoute =
  ApiPublicWorkerHeartbeatRouteImport.update({
    id: '/api/public/worker/heartbeat',
    path: '/api/public/worker/heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWorkerIngestRoute = ApiPublicWorkerIngestRouteImport.update({
  id: '/api/public/worker/ingest',
  path: '/api/public/worker/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerJobsRoute = ApiPublicWorkerJobsRouteImport.update({
  id: '/api/public/worker/jobs',
  path: '/api/public/worker/jobs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/groups': typeof GroupsRoute
  '/insights/': typeof InsightsIndexRoute
  '/api/public/worker/complete': typeof ApiPublicWorkerCompleteRoute
  '/api/public/worker/heartbeat': typeof ApiPublicWorkerHeartbeatRoute
  '/api/public/worker/ingest': typeof ApiPublicWorkerIngestRoute
  '/api/public/worker/jobs': typeof ApiPublicWorkerJobsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/groups': typeof GroupsRoute
  '/insights': typeof InsightsIndexRoute
  '/api/public/worker/complete': typeof ApiPublicWorkerCompleteRoute
  '/api/public/worker/heartbeat': typeof ApiPublicWorkerHeartbeatRoute
  '/api/public/worker/ingest': typeof ApiPublicWorkerIngestRoute
  '/api/public/worker/jobs': typeof ApiPublicWorkerJobsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/groups': typeof GroupsRoute
  '/insights/': typeof InsightsIndexRoute
  '/api/public/worker/complete': typeof ApiPublicWorkerCompleteRoute
  '/api/public/worker/heartbeat': typeof ApiPublicWorkerHeartbeatRoute
  '/api/public/worker/ingest': typeof ApiPublicWorkerIngestRoute
  '/api/public/worker/jobs': typeof ApiPublicWorkerJobsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/groups'
    | '/insights/'
    | '/api/public/worker/complete'
    | '/api/public/worker/heartbeat'
    | '/api/public/worker/ingest'
    | '/api/public/worker/jobs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/groups'
    | '/insights'
    | '/api/public/worker/complete'
    | '/api/public/worker/heartbeat'
    | '/api/public/worker/ingest'
    | '/api/public/worker/jobs'
  id:
    | '__root__'
    | '/'
    | '/groups'
    | '/insights/'
    | '/api/public/worker/complete'
    | '/api/public/worker/heartbeat'
    | '/api/public/worker/ingest'
    | '/api/public/worker/jobs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GroupsRoute: typeof GroupsRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  ApiPublicWorkerCompleteRoute: typeof ApiPublicWorkerCompleteRoute
  ApiPublicWorkerHeartbeatRoute: typeof ApiPublicWorkerHeartbeatRoute
  ApiPublicWorkerIngestRoute: typeof ApiPublicWorkerIngestRoute
  ApiPublicWorkerJobsRoute: typeof ApiPublicWorkerJobsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/complete': {
      id: '/api/public/worker/complete'
      path: '/api/public/worker/complete'
      fullPath: '/api/public/worker/complete'
      preLoaderRoute: typeof ApiPublicWorkerCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/heartbeat': {
      id: '/api/public/worker/heartbeat'
      path: '/api/public/worker/heartbeat'
      fullPath: '/api/public/worker/heartbeat'
      preLoaderRoute: typeof ApiPublicWorkerHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/ingest': {
      id: '/api/public/worker/ingest'
      path: '/api/public/worker/ingest'
      fullPath: '/api/public/worker/ingest'
      preLoaderRoute: typeof ApiPublicWorkerIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/jobs': {
      id: '/api/public/worker/jobs'
      path: '/api/public/worker/jobs'
      fullPath: '/api/public/worker/jobs'
      preLoaderRoute: typeof ApiPublicWorkerJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GroupsRoute: GroupsRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  ApiPublicWorkerCompleteRoute: ApiPublicWorkerCompleteRoute,
  ApiPublicWorkerHeartbeatRoute: ApiPublicWorkerHeartbeatRoute,
  ApiPublicWorkerIngestRoute: ApiPublicWorkerIngestRoute,
  ApiPublicWorkerJobsRoute: ApiPublicWorkerJobsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
